language: python
python: "2.7"
branches:
  only:
    - noreg_order
notifications:
  irc: "irc.freenode.org#starzel"
install:
  - mkdir -p buildout-cache/eggs
  - mkdir -p buildout-cache/downloads
  - python bootstrap.py -c travis.cfg
  - bin/buildout -N -t 3 -c travis.cfg
script: bin/test
